project:
  type: website

website:
  title: "Class Wiki for Childhood Psychopathology (FALL 2025)"
  repo-url: https://github.com/isaactpetersen/psy-3330-2025-fall
  repo-actions: [edit, source, issue]
  google-analytics: G-Q2P48ZXWTS
  navbar:
    title: "Class Wiki for Childhood Psychopathology (FALL 2025)"
    search: true
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/isaactpetersen/psy-3330-2025-fall
          - text: "Report a Bug"
            href: https://github.com/isaactpetersen/psy-3330-2025-fall/issues/new
    left:
      - href: index.qmd
        text: Home
      - text: "Course Syllabus"
        href: syllabus.qmd
      - text: "Miscellaneous"
        menu:
        - text: I Think I Might Need Some Help...
          href: help.qmd
        - text: Opportunity to Join My Research Lab!
          href: devpsylab.qmd
      - about.qmd

format:
  html:
    highlight-style: a11y
    theme: cosmo
    css: ["styles.css", "includes/custom.css", "font/css/roboto.css"]
    toc: true
    toc-depth: 5
    toc-title: Contents
    toc-location: right
    execute:
      error: true
      warning: false
    code-link: true
    number-sections: true
    code-fold: show
    df-print: paged
    code-tools:
      source: true
      toggle: true
    link-external-newwindow: true
    #include-in-header:
    #  - "includes/google_analytics.html"
    #include-after-body:
    #  - "includes/footer.html"
    license: CC BY
    author-meta: "Isaac T. Petersen"
    date-meta: today
  pdf:
    keep-tex: true
    license: false

lightbox: 
  match: auto
